---
name: food_market
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  google_fonts: ^2.0.0
  supercharged: ^2.0.0
  flutter_spinkit: ^5.0.0
  get: ^4.0.0-nullsafety.2
  material_design_icons_flutter: ^4.0.5955
  intl: ^0.17.0
  equatable: ^2.0.0
  http: ^0.13.1
  image_picker: ^0.7.3
  url_launcher: ^5.7.2
  hydrated_bloc: ^7.0.0
  path_provider: ^2.0.1
  json_annotation: ^3.1.1
  get_storage: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  json_serializable: ^3.5.1
flutter:
  uses-material-design: true
  assets:
  - assets/
